import {
  ToolTipSection,
  ToolTipsMainContainer,
} from '../../Liquidity/LiquidityHomePage/styles/LiquidityToolTipStyle';
import { LockHeaderTitle } from '../../ManageVeTenex/Styles/ManageVetenex.style';
import { VotingTitle } from '../styles/VotingBanner.style';

const VotingToolTips = () => {
  return (
    <ToolTipSection fontSize={12}>
      <LockHeaderTitle fontSize={24}>Voting</LockHeaderTitle>
      <ToolTipsMainContainer>
        <VotingTitle fontSize={12}>
          $veTENEX holders play a crucial role in directing $TENEX emissions to
          various liquidity pools. In exchange for their governance, they earn
          all trading fees and incentives generated by the pools they vote for.
        </VotingTitle>
        <LockHeaderTitle fontSize={16}>Timeline</LockHeaderTitle>
        <VotingTitle fontSize={12}>
          To participate in the voting process, ensure your votes are submitted
          by Wednesday at 23:00 UTC, just before the new epoch starts. There
          will be a two-hour window immediately after during which voting is
          paused for protocol maintenance and automation.
        </VotingTitle>
        <LockHeaderTitle fontSize={16}>Instructions</LockHeaderTitle>
        <VotingTitle fontSize={12}>
          Allocate your total vote-power from $veTENEX (veNFT) to your preferred
          liquidity pools and cast your vote. If you possess multiple $veTENEX
          (veNFTs), you will need to cast votes for each separately. Any
          vote-power left unallocated will be distributed proportionally among
          your selected pools. Each $veTENEX (veNFT) can only vote once per
          epoch, and if you gain additional $veTENEX (veNFTs) during the epoch,
          recast your vote to ensure full allocation. Votes not altered will
          carry forward to the next epoch.
        </VotingTitle>
        <LockHeaderTitle fontSize={16}>Rewards</LockHeaderTitle>
        <VotingTitle fontSize={12}>
          You will see your voting rewards in your Dashboard after the epoch
          transition at Thursday 00:00 UTC. New $veTENEX (veNFT) rebase rewards
          will be updated after the second epoch change.
        </VotingTitle>
      </ToolTipsMainContainer>
    </ToolTipSection>
  );
};

export default VotingToolTips;
